// admin login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "userEmail": "user@example.com",
    "password": "1234567"
}

###
// verify token
GET http://localhost:5000/api/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaXNBZG1pbiI6MCwiaWF0IjoxNjU0MTM5ODgyfQ.ZRlDnmniCB-AmzdC_lq031PC6A1mXbfpzeY-bazFwmI

###
// create user
POST http://localhost:5000/api/create
Content-Type: application/json

{
    "userEmail": "user@example.com",
    "password": "1234567",
    "userFirstName": "test",
    "userLastName": "asda"
    
}

###
// change the password
PATCH http://localhost:5000/api/change-password
Content-Type: application/json

{
    "userEmail": "user@example.com",
    "prevPassword": "123456",
    "newPassword": "1234567"
}

