@baseUrl=http://localhost:5000/v2/api/users

### REGISTER
POST {{baseUrl}}/register
content-type: application/json

{
    "fistname": "Ha",
    "lastname": "Tan",
    "email": "hatrongtan99@gmail.com",
    "password": "123456",
    "avatar": ""
}

#### LOGIN
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "hatrongtan99@gmail.com",
    "password": "123456"
}

### LOGOUT
GET {{baseUrl}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlhOTU0MGUwN2M0YTgzODE0YjBiNzYiLCJlbWFpbCI6ImhhdHJvbmd0YW45OUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTY3MTI1MjYwNSwiZXhwIjoxNjcxMjU2MjA1fQ.K-CKDJ6O2jyuam7O7qHN-_dWtYc_OunQFoAOMxf-fSY

### refresh Token
GET {{baseUrl}}/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlhOTU0MGUwN2M0YTgzODE0YjBiNzYiLCJlbWFpbCI6ImhhdHJvbmd0YW45OUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTY3MTI1MjY2MCwiZXhwIjoxNjcxMjU2MjYwfQ.U9g81bxcVm8rBXN61hLK7nrz1Lh3LHNkb_QE51giY48

### GET PROFILE
GET {{baseUrl}}/639a9540e07c4a83814b0b76
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlhOTU0MGUwN2M0YTgzODE0YjBiNzYiLCJlbWFpbCI6ImhhdHJvbmd0YW45OUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTY3MTI1MjY2MCwiZXhwIjoxNjcxMjU2MjYwfQ.U9g81bxcVm8rBXN61hLK7nrz1Lh3LHNkb_QE51giY48

### GET ALL USERS
GET {{baseUrl}}/all-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzlhOTU0MGUwN2M0YTgzODE0YjBiNzYiLCJlbWFpbCI6ImhhdHJvbmd0YW45OUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTY3MTI1MjY2MCwiZXhwIjoxNjcxMjU2MjYwfQ.U9g81bxcVm8rBXN61hLK7nrz1Lh3LHNkb_QE51giY48
###
GET {{baseUrl}}/test-token
